DROP DATABASE IF EXISTS web_recetas;

CREATE DATABASE web_recetas;

USE web_recetas;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT UNSIGNED AUTO_INCREMENT,
  username VARCHAR(20),
  email VARCHAR(50),
  passwd VARCHAR(100),
  permisos TINYINT(1),
  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS recetas (
  id INT UNSIGNED AUTO_INCREMENT,
  elaboracion DATETIME,
  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS ingredientes (
  id INT UNSIGNED AUTO_INCREMENT,
  id_receta INT UNSIGNED,
  PRIMARY KEY(id),
  FOREIGN KEY(id_receta) REFERENCES recetas(id)
);